import { z } from 'zod';

export const productFormSchema = z.object({
  title: z.string().min(1, '商品名稱為必填'),
  slug: z.string().min(1, 'Slug 為必填').regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Slug 格式不正確（僅小寫英文、數字和連字號）'),
  price: z.number().min(0, '價格不可為負數'),
  discount_price: z.number().min(0, '折扣價不可為負數').nullable().optional(),
  sku: z.string().nullable().optional(),
  desc_text: z.string().nullable().optional(),
  availability: z.string().nullable().optional(),
  size: z.string().nullable().optional(),
  color: z.string().nullable().optional(),
  tag: z.string().nullable().optional(),
  is_featured: z.boolean().optional(),
  is_new_arrival: z.boolean().optional(),
  show_in_banner: z.boolean().optional(),
  banner_order: z.number().int().optional(),
  is_active: z.boolean().optional(),
  sort_order: z.number().int().optional(),
  content: z.string().nullable().optional(),
  xs_image: z.string().nullable().optional(),
  sm_image: z.string().nullable().optional(),
  md_image: z.string().nullable().optional(),
  home_collection_img: z.string().nullable().optional(),
  category_banner_img: z.string().nullable().optional(),
  alt_image: z.string().nullable().optional(),
  sold_out_sticker: z.string().nullable().optional(),
  best_seller_sticker: z.string().nullable().optional(),
  offer_sticker: z.string().nullable().optional(),
  category_ids: z.array(z.string().uuid()).optional(),
});

export type ProductFormData = z.infer<typeof productFormSchema>;

// Schema for API routes that receive JSON (needs coercion from string → number)
export const productApiSchema = z.object({
  title: z.string().min(1, '商品名稱為必填'),
  slug: z.string().min(1, 'Slug 為必填').regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, 'Slug 格式不正確'),
  price: z.coerce.number().min(0, '價格不可為負數'),
  discount_price: z.preprocess(
    (v) => (v === '' || v === null || v === undefined ? null : Number(v)),
    z.number().min(0, '折扣價不可為負數').nullable().optional(),
  ),
  sku: z.string().nullable().optional(),
  desc_text: z.string().nullable().optional(),
  availability: z.string().nullable().optional(),
  size: z.string().nullable().optional(),
  color: z.string().nullable().optional(),
  tag: z.string().nullable().optional(),
  is_featured: z.boolean().default(false),
  is_new_arrival: z.boolean().default(false),
  show_in_banner: z.boolean().default(false),
  banner_order: z.coerce.number().int().default(0),
  is_active: z.boolean().default(true),
  sort_order: z.coerce.number().int().default(0),
  content: z.string().nullable().optional(),
  xs_image: z.string().nullable().optional(),
  sm_image: z.string().nullable().optional(),
  md_image: z.string().nullable().optional(),
  home_collection_img: z.string().nullable().optional(),
  category_banner_img: z.string().nullable().optional(),
  alt_image: z.string().nullable().optional(),
  sold_out_sticker: z.string().nullable().optional(),
  best_seller_sticker: z.string().nullable().optional(),
  offer_sticker: z.string().nullable().optional(),
  category_ids: z.array(z.string().uuid()).default([]),
});
